<div class="content-header">
    <table cellspacing="0"><tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head"><?= $this->__('Manage Cloudinary Images') ?></h3></td>
            <td class="form-buttons">
                <?= $this->getMigrateButton() ?>
                <?= $this->getEnableButton() ?>
            </td>
        </tr>
    </tbody></table>
</div>

<p>
    <?php if ($this->allImagesSynced()): ?>
        <div id="messages">
            <ul class="messages">
                <li class="notice-msg">
                    <ul><li><span><?= $this->__('All images have been successfully exported to Cloudinary') ?></span></li></ul>
                </li>
            </ul>
        </div>
    <?php else: ?>
        <p><?= $this->__('Image export progress: %s%', floor($this->getPercentComplete())) ?></p>
        <p><?= $this->__('%s of %s images exported to Cloudinary.', $this->getSyncedImageCount(), $this->getTotalImageCount())?></p>
    <?php endif; ?>
</p>

<p>
    <strong>
        <?= $this->__('Note: If you have a lot of images (thousands or more), image export may take a while') ?>.
        <?= $this->__('You can leave this page and come back to check on progress while the export is performed in the background') ?>.
    </strong>
</p>


<p>
    <strong><?= $this->__('Looking for more information?') ?></strong>
    <a href="http://support.cloudinary.com/hc/en-us/sections/200956331-Magento" target="_blank"><?= $this->__('Visit our Knowledge Base') ?></a>.
</p>

<p>
    <strong><?= $this->__('Need assistance or got feedback?') ?></strong>
    <a href="http://support.cloudinary.com/hc/en-us/requests/new" target="_blank"><?= $this->__('Contact our support') ?></a>.
</p>
